Quote command line parameters (except for Windows)
perl6/nqp-configure pull request #23
Opened 2020-07-12 13:45 UTC by usev6

This compensates for https://github.com/Raku/nqp/commit/1517cf77db
and unbreaks nqp-j on non-Windows systems.
Fixes https://github.com/Raku/nqp/issues/644

2020-07-12 13:51 UTC, usev6 commented
This is a bit hacky, but should work. If I'm not mistaken, ```sh_allparams``` is only used in https://github.com/Raku/nqp/blob/db0c1088fc/tools/templates/jvm/nqp-j.in#L10

A somewhat cleaner approach would probably be to add a new variable like ```@sh_params_quote``` that is the empty string on Windows and a ```"``` otherwise.

2020-07-12 20:41 UTC, vrurg commented
The patch breaks the whole meaning of the parameter. Same problem with the "conditional quote" parameter you propose – it's way too specific, as I understand. Unfortunately, I'm not an expert in all Windows quirks and oddities. But so far I can see that the problem is only related to the "all params" shell variable. If it's true then better solution is to have on more parameter `sh_allparams_quoted` which would utilize your hack except that in this case it's not a hack anymore.

Another good solution would be a new macro in addition to `@shquot()@` which would quote conditionally, depending on the current platform. Something like `@shquot_soft()@`. But this approach would make sense if there're other cases when Windows requires quote omission contrary to normal platforms.

@patrickbkr do you have suggestions? You know Win better than I do.

2020-07-12 20:42 UTC, vrurg requested changes
Not in this form.

2020-07-12 20:43 UTC, vrurg commented
Ah, and in either case the good fix would involve patching of _nqp-j.in_.

2020-07-12 21:00 UTC, usev6 commented
@vrurg thanks for looking. Unfortunately, it's not easy for me to test on Windows and I'm not familiar with it anyway. (I just noticed that nqp-j is broken and looked for a simple way to repair it.)

You mentioned an additional parameter ```sh_allparams_quoted```. If I'm not mistaken, in that case ```sh_allparams``` wouldn't be used anymore -- at least not for NQP or Rakudo. Would you prefer to keep it or could it go away -- which would basically mean that ```sh_allparams``` should be renamed in addition to the added quotes (also in ```nqp-j.in```)?

2020-07-12 22:19 UTC, vrurg commented
`sh_allparams` is better stay where it is for now. We may remove it in the future. Anyway, I'd like to hear from @patrickbkr first.

2020-07-13 17:25 UTC, patrickbkr commented
From my knowledge (No guarantees!) there is no mechanism to reliably quote things on Windows when CMD is involved. So I think there won't be much of a point in trying to create an abstraction to do quoting reliably on CMD.
Having quickly glanced at the `nqp-j.in` file there is already an `@if()` statement involved. We may just as well add another one adding quotes conditionally. Alternatively we could just take the leap and have separate `nqp-j.in` files for Windows and the rest. Given that one is a bat file and the other a shell script this isn't far fetched.

2020-07-15 14:22 UTC, vrurg commented
> From my knowledge (No guarantees!) there is no mechanism to reliably quote things on Windows when CMD is involved. So I think there won't be much of a point in trying to create an abstraction to do quoting reliably on CMD.

This is exactly the reason I summoned you into this PR!

> Having quickly glanced at the `nqp-j.in` file there is already an `@if()` statement involved. We may just as well add another one adding quotes conditionally. Alternatively we could just take the leap and have separate `nqp-j.in` files for Windows and the rest. Given that one is a bat file and the other a shell script this isn't far fetched.

I didn't like any kind of splitting because if the command line executing java would ever change it will require changing in both files what makes a good source of potential errors. But keeping in mind that a big part of the template is already wrapped into two platform-testing `@if()@` macros; and that the purpose of the wrap is to handle quotes – I think splitting is the lesser of two evils.

@usev6 I'm closing this PR as the fix should be done in nqp repo.

2020-07-15 14:22 UTC, closed without merging